# Generated by Django 5.2.17 on 2026-10-05 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('checked', models.BooleanField(default=False)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('packed', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('source', models.CharField(max_length=20)),
                ('arrival_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='logistica.item')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('carrier', models.CharField(max_length=150)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='logistica.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Data necessária')),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistica.order'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='logistica.order')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Obra')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço de entrega')),
                ('active', models.BooleanField(default=True)),
                ('supervisors', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.project'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='draft', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('destination', models.CharField(default='depot', max_length=10)),
                ('expected', models.DateField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='logistica.item')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='logistica.purchase'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recipient', models.CharField(max_length=150)),
                ('delivered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='logistica.dispatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('received__gte', 0), ('received__lte', models.F('quantity'))), name='dispatch_in_range'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_positive'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0), ('stock_quantity__lte', models.F('quantity'))), name='stock_in_range'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('packed__gte', 0), ('packed__lte', models.F('quantity'))), name='lot_in_range'),
        ),
    ]
